### PR TITLE
Removed white-space:nowrap

### PR DESCRIPTION
**Pull request by bedhed**
This line breaks layout on Mozilla Firefox and does not really help anywhere else.
See https://github.com/yahoo/pure/issues/644

### CODE REVIEW

**Comment by redonkulus** [comment]
@bedhed thanks for this. Were you able to test it across browsers? Its could break things in older browsers.

**Comment by bedhed** [comment]
Tested only on Chromium 59.0.3071.109 & Firefox 54.0. Sorry.

**Comment by redonkulus** [comment]
Ok thanks. This will require more testing before we can release it. Any help is appreciated.

**Comment by redonkulus** [comment]
Related https://github.com/yahoo/pure/issues/497

**Comment by redonkulus** [comment]
@bedhed the one thing delaying this PR from being merged is browser testing. At the least it would need to be tested on IE8+ and Android 4+ to ensure there are no breaking changes.

**Pull request closed without merging**
