### PR TITLE
update dependance

### PR DESCRIPTION
**Pull request by ValentinGratz**
Please consider the following before submitting a pull request:

Guidelines for contributing: https://github.com/pure-css/pure/blob/master/CONTRIBUTING.md

Example of changes on an interactive website such as the following:

- http://jsbin.com/
- http://jsfiddle.net/
- http://codepen.io/pen/

---

I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by redonkulus** [comment]
The commit history is a bit noisy, you might want to rebase from master to clean it up.

What does v7 of gzip-size bring in? Is it ESM only, if so, that would be a breaking change in our package for end users.

**Comment by ValentinGratz** [comment]
> L’historique des validations est un peu bruyant, vous voudrez peut-être rebaser à partir du maître pour le nettoyer.
> 
> Qu’est-ce que v7 de gzip-size apporte? Est-ce uniquement ESM, si c’est le cas, ce serait un changement radical dans notre package pour les utilisateurs finaux.

I don't know what more it can bring.
I'm not an expert, I just wanted to contribute by updating the security packages with dependabot from github.

**Comment by redonkulus** [comment]
gzip-size v7 is [ESM only](https://github.com/sindresorhus/gzip-size/releases/tag/v7.0.0) and will require code changes in the site files to support this change. You would need to run the site locally and update the code that uses gzip-size to ensure the site works properly with version 7.

**Comment by redonkulus** [comment]
Going to close this for now, please re-open if you would like to make the code changes.

**Pull request closed without merging**
