### PR TITLE
Removing font specific settings from Grid and Button.

### PR DESCRIPTION
**Pull request by koculu**
Please remove font related settings from purecss. Instead you can provide an optional file to set those details for those who are interested. Adding those font families by default is a conflict with the name pure.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by redonkulus** [comment]
Looks like you removed the letter spacing hacks as well. Was this intentional?

**Comment by koculu** [comment]
Hi redonkulus, I removed all font related settings. In my opinion any font&appearance related properties must be in another file and better to have it optional. If you accept this PR at least we would get rid of dictated font decisions and letter spacings for Grid Layout. There is more work required on one of the grunt tasks. **grunt-pure-grids** In this task there exist font adjustments as well (ex: letter-spacings)
Grid Layout''s Single Responsibility is layout management but not text adjustments.

**Comment by koculu** [comment]
If you agree with my opinion, we need to get rid of font related declarations on this file:
https://github.com/pure-css/rework-pure-grids/edit/master/index.js

**Comment by redonkulus** [comment]
The letter spacing hacks were there to ensure cross browser compatibility. Obviously these were for browsers that very out of date now and probably not necessary. Have you tested these changes across the modern browsers?

**Pull request closed without merging**
